services:
  keras-container:
    build: .
    container_name: "kerasContainer__"

    command: bash
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    volumes:
      - ./code:/home/Projects/

    tty: true

    restart: on-failure

    privileged: true